config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :posts
  resources :comments, only:[:create, :destroy]
  root 'posts#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :post
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates :body,    presence: true
  validates :post_id, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
  has_many :comment
  validates :title,    presence:true
  validates :category, presence:true
  scope :post_order, ->{order(:category_id)}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :family_name
    devise_parameter_sanitizer.for(:sign_up) << :gien_name
    devise_parameter_sanitizer.for(:account_update) << :family_name
    devise_parameter_sanitizer.for(:account_update) << :given_name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to post_url(@comment.post_id)
    else
      redirect_to post_url(@comment.post_id)
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    post_id = @comment.post_id
    @comment.destroy
    redirect_to post_url(post_id)
  end

  private
  def comment_params
    params.require(:comment).permit(
      :body,
      :post_id
    )
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :search_post, only:[:show, :edit, :update, :destroy]
  before_action :authenticate_user!# only:[:show, :edit, :update, :destroy]
  def index
    @q = Post.post_order.ransack(params[:q])
    @posts = @q.result.page(params[:page])


  end

  def create
    @post = Post.new(post_params)
    @post.save
    redirect_to @post
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = Comment.where(post_id: params[:id].to_i)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update_attributes(post_params)
    @post.save
    redirect_to post_url(@post)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    @post.save
    redirect_to posts_url(@post)
  end

  private
  def search_post
    @post = Post.find(params[:id])
  end
  def post_params
    params.require(:post).permit(
      :title,
      :content,
      :category,
      :category_id
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header" style="float:left;">
      <a class="navbar-brand" href="<%= posts_path %>">
        <%= image_tag("smart-home-icon.png", height:30) %>
      </a>
    </div>
    <h1>Test Blog</h1>
  </div>
  <div style="float:right">
  <ul>
  <% if user_signed_in? %>
    <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
    <li><%= link_to '設定変更', edit_user_registration_path %></li>
  <% else %>
    <li><%= link_to '新規登録', new_user_registration_path %></li>
    <li><%= link_to 'Sign in', new_user_session_path %></li>
  <% end %>
  </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>
<body>
<%= render 'layouts/header' %>
  <div class="container">
  <% if notice.present? %>
    <div class="alert alert-dismissable alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <p><%= notice %></p>
    </div>
  <% end %>

  <% if alert.present? %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <p><%= alert %></p>
    </div>
  <% end %>

<%= yield %>


      </div>
      <div class="col-xs-6 col-md-8">
    </div>
  </div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<div>
  <%= f.label 'Title:' %>
  <%= f.text_field :title %>
</div>
<div>
  <%= f.label 'Content:' %>
  <%= f.text_area :content %>
</div>
<div>
  <%= f.label :category_id %>
  <%= f.collection_select(:category_id, Category.all, :id, :genre) %>
</div>

<%= f.submit 'Entry' %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Blog</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<h2>Title List</h2>
<div>
  <form class="navbar-form" role="search">
    <div class="form-group navbar-left">
    <%= search_form_for @q do |f| %>
    <%= f.label :title_or_content_cont, 'Search' %>
    <%= f.search_field :title_or_content_cont %>

      <!--<input type="text" class="form-control" placeholder="Search">-->
    </div>
    <%= f.submit 'Search' %>
    <% end %>
    <!--<button type="submit" class="btn btn-default">Submit</button>-->
  </form>
</div>
<hr/>
<ul>
<% @posts.each do |post| %>
  <li><a href="posts/<%= post.id %>"><%= post.title %></li></a>
<% end %>
</ul>
<%= link_to 'Entry', new_post_path %>
<div class="text-center">
  <%= paginate @posts %>
</div>

app/views/posts/new.html.erb
<h1>New Entry</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<div>
  <strong>Title:</strong><%= @post.title %>
</div>
<div>
  <strong>content:</strong><br/><%= @post.content %>
</div>
<div>
  <strong>category:</strong><%= @post.category.genre %>
</div>
<div class="comment">
  <% @comments.each do |comment| %>
      <div class="media">
        <div class="media-body">
          <p><%= simple_format(comment.body) %></p>
          <p class="text-muted">
            投稿日時：<%= comment.created_at.strftime('%Y/%m/%d %H:%M') %>
            <%= link_to "削除", comment_path(comment), method: :delete %>
          </p>
        </div>
      </div>
    <% end %>
</div>
  <%= form_for @comment, url: {controller: :comments, action: :create} do |f| %>
<div>
  <%= f.label :body, 'コメント内容：' %><br/>
  <%= f.text_area :body %>
</div>
  <%= f.hidden_field :post_id, value: @post.id %>
  <%= f.submit %>
  <% end %>
<%= link_to 'Back to TOP', posts_path %>
<%= link_to 'Edit', edit_post_path %>
<%= link_to 'Delete', post_path, method: :delete %>